### ISSUE TITLE
Examples, please

### ISSUE THREAD

**Issue by aegontargaryen-dev** [portlek/scoreboard#44]
Hi there! It would be great if you could write some examples of how to use this library.
Great work by the way, seems like the code is well written :)

**Comment by portlek** [comment]
thanks :D yea i didn't write any example for it. i will write some of examples into the readme file today.

**Comment by portlek** [comment]
Done @yiatzz You can examine the readme.

**Comment by aegontargaryen-dev** [comment]
> Done @yiatzz You can examine the readme.

i appreciate it <3

**Comment by aegontargaryen-dev** [comment]
btw how can i contact u? discord maybe?

**Comment by portlek** [comment]
@portlek portlek#5502
